/**
 * Seed data for Shakti Global Tex — handcrafted home textiles.
 * 43 products, one per catalogue image:
 *   Bathmat 1–6 · Pillow 1–5 · Pouf 1–4 · Rug And Carpets 1–9 · Throw 1–19
 * Ranges (GSM, sizes, MOQs) are representative export-catalogue values;
 * every field is editable via the Admin dashboard.
 */

const PRODUCTS = [
  // ───────────────────────── Bathmats (6) ─────────────────────────
  {
    slug: 'cotton-reversible-bath-mat',
    name: 'Cotton Reversible Bath Mat',
    category: 'Bathmat',
    image: '/products/bathmat/1.jpg',
    shortDescription: 'Heavy 500 GSM reversible cotton bath mat with woven-in borders — soft on both faces.',
    description:
      'Our signature bath mat, woven from 100% ring-spun cotton at a dense 500 GSM so it feels plush underfoot yet dries quickly. Fully reversible — the pattern is woven, not printed, so both faces look finished. Repeated commercial laundering does not flatten the pile, which is why hotel chains re-order it season after season.',
    benefits: [
      'Reversible weave — two finished faces, doubles service life',
      'High-absorbency 500 GSM ring-spun cotton',
      'Survives 60°C commercial laundering without pile collapse',
    ],
    specs: [
      { label: 'Sizes', value: '50 × 80 cm · 60 × 90 cm · 70 × 120 cm runner' },
      { label: 'Material', value: '100% ring-spun cotton' },
      { label: 'Weight', value: '500 GSM' },
      { label: 'Care', value: 'Machine wash 60°C, tumble dry low' },
      { label: 'Colours', value: '12 stock shades; custom dyeing from 300 pcs' },
      { label: 'Packing', value: 'Individual polybag + hangtag; 40 pcs per carton' },
    ],
    industries: ['Hospitality & Hotels', 'Retail & Private Label'],
    certifications: ['OEKO-TEX', 'ISO 9001'],
    tags: ['Best seller', 'Reversible'],
    minOrderQty: '300 pcs per shade',
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'tufted-anti-slip-bath-mat',
    name: 'Tufted Anti-Slip Bath Mat',
    category: 'Bathmat',
    image: '/products/bathmat/2.jpg',
    shortDescription: 'Hand-tufted cotton pile with a spray-latex anti-slip back — safe on wet tiles.',
    description:
      'Hand-tufted cut-pile cotton with a high-low texture that massages the feet and hides water marks between cleans. The spray-latex backing grips wet ceramic and stone tiles securely and is formally tested for slip resistance. A workhorse for hotel bathrooms and spa changing rooms.',
    benefits: [
      'Spray-latex anti-slip backing, tested on wet tile',
      'Hand-tufted high-low pile texture',
      'Latex back retains grip after 50+ washes',
    ],
    specs: [
      { label: 'Sizes', value: '50 × 80 cm · 60 × 90 cm · 90 × 60 cm bath set' },
      { label: 'Material', value: 'Cotton pile with latex anti-slip back' },
      { label: 'Weight', value: '1,400 – 1,800 GSM total' },
      { label: 'Pile height', value: '12 – 15 mm cut pile' },
      { label: 'Care', value: 'Machine wash 40°C; do not iron backing' },
      { label: 'Packing', value: 'Polybag; vacuum-packed 30 pcs per carton' },
    ],
    industries: ['Hospitality & Hotels', 'Interior Studios & Designers'],
    certifications: ['OEKO-TEX'],
    tags: ['Anti-slip'],
    minOrderQty: '300 pcs per shade',
    featured: false,
    sortOrder: 2,
  },
  {
    slug: 'waffle-weave-bath-mat',
    name: 'Waffle Weave Bath Mat',
    category: 'Bathmat',
    image: '/products/bathmat/3.jpg',
    shortDescription: 'Lightweight waffle-weave mat that dries in half the time of terry — spa favourite.',
    description:
      'Woven in a classic waffle structure that channels water into the cells and dries fast — ideal where mats are laundered daily. Thin enough to fold crisply for retail gifting, sturdy enough for daily housekeeping trolleys. Popular with spas and boutique hotels that want a clean, tailored look.',
    benefits: [
      'Fast-drying waffle cells — ready again in hours',
      'Lightweight, folds flat for retail packaging',
      'Minimal lint, ideal for daily laundering',
    ],
    specs: [
      { label: 'Sizes', value: '50 × 80 cm · 60 × 90 cm · 80 × 140 cm' },
      { label: 'Material', value: '100% cotton waffle weave' },
      { label: 'Weight', value: '320 – 400 GSM' },
      { label: 'Care', value: 'Machine wash 60°C, low tumble' },
      { label: 'Colours', value: 'White, ivory, grey, charcoal; custom shades from 500 pcs' },
      { label: 'Packing', value: 'Polybag; 50 pcs per carton' },
    ],
    industries: ['Hospitality & Hotels', 'Retail & Private Label', 'Gifting & E-commerce'],
    certifications: ['OEKO-TEX'],
    tags: ['Fast drying'],
    minOrderQty: '500 pcs per shade',
    featured: false,
    sortOrder: 3,
  },
  {
    slug: 'chenille-strip-bath-mat',
    name: 'Chenille Strip Bath Mat',
    category: 'Bathmat',
    image: '/products/bathmat/4.jpg',
    shortDescription: 'Ultra-absorbent chenille strips on a non-slip mesh back — the softest step in the range.',
    description:
      'Plush microfibre chenille strips are sewn onto a durable non-slip mesh backing, creating deep channels that hold several times their weight in water. The softest underfoot feel we make, and the fastest to dry because the strips stand apart. A strong retail performer in gift and bath-set packs.',
    benefits: [
      'Chenille strips hold 4–5× their weight in water',
      'Textured PVC-dot mesh back grips all floor types',
      'Machine washable without clumping',
    ],
    specs: [
      { label: 'Sizes', value: '40 × 60 cm · 50 × 80 cm · 45 × 120 cm runner' },
      { label: 'Material', value: 'Microfibre chenille + TPR/mesh backing' },
      { label: 'Pile height', value: '25 mm shaggy strips' },
      { label: 'Care', value: 'Machine wash 30°C, air dry' },
      { label: 'Colours', value: '8 stock colours; two-tone combos on request' },
      { label: 'Packing', value: 'Polybag with insert card; 36 pcs per carton' },
    ],
    industries: ['Retail & Private Label', 'Gifting & E-commerce'],
    certifications: ['OEKO-TEX'],
    tags: ['Retail favourite'],
    minOrderQty: '500 pcs per colour',
    featured: false,
    sortOrder: 4,
  },
  {
    slug: 'two-tone-bordered-bath-mat',
    name: 'Two-Tone Bordered Bath Mat',
    category: 'Bathmat',
    image: '/products/bathmat/5.jpg',
    shortDescription: 'Contrast-border cotton mat, woven to your brand palette — private-label ready.',
    description:
      'A tailored flat-pile mat with a contrast woven border, developed for private-label programmes where the mat must match the towel line. Borders and body are dyed to Pantone references in the same batch, so shades stay matched across repeat orders. Embroidered or woven labels can be added at the hem.',
    benefits: [
      'Border + body dyed to Pantone in one batch',
      'Private-label hem labels: woven or embroidered',
      'Flat pile fits under doors and robe hooks',
    ],
    specs: [
      { label: 'Sizes', value: '50 × 80 cm · 60 × 90 cm' },
      { label: 'Material', value: '100% cotton, flat-woven pile' },
      { label: 'Weight', value: '450 – 550 GSM' },
      { label: 'Care', value: 'Machine wash 40°C' },
      { label: 'Colour options', value: 'Any Pantone shade, 2-colour border combinations' },
      { label: 'Packing', value: 'Polybag; 40 pcs per carton' },
    ],
    industries: ['Retail & Private Label', 'Hospitality & Hotels'],
    certifications: ['OEKO-TEX', 'SEDEX'],
    tags: ['Private label', 'Custom dye'],
    minOrderQty: '500 pcs per colourway',
    featured: false,
    sortOrder: 5,
  },
  {
    slug: 'textured-loop-bath-mat',
    name: 'Textured Loop Bath Mat',
    category: 'Bathmat',
    image: '/products/bathmat/6.jpg',
    shortDescription: 'Chunky loop-pile cotton mat with a handwoven character and rugged durability.',
    description:
      'Woven with oversized loop pile on handloom-width looms, this mat brings a handcrafted, tactile character to the bathroom. The loop structure is naturally hard-wearing and hides footprints and lint between washes. Each piece carries slight loom-to-loom variation that buyers of artisan textiles actively look for.',
    benefits: [
      'Handloom loop pile with artisan character',
      'Extremely durable — ideal for high-traffic bathrooms',
      'Stock shades ship in 7 days',
    ],
    specs: [
      { label: 'Sizes', value: '50 × 80 cm · 60 × 90 cm · 70 × 140 cm' },
      { label: 'Material', value: '100% cotton loop pile' },
      { label: 'Weight', value: '900 – 1,100 GSM' },
      { label: 'Care', value: 'Machine wash 40°C, line dry' },
      { label: 'Colours', value: '6 earthy stock shades' },
      { label: 'Packing', value: 'Folded polybag; 30 pcs per carton' },
    ],
    industries: ['Interior Studios & Designers', 'Retail & Private Label'],
    certifications: ['OEKO-TEX', 'GOTS'],
    tags: ['Handloom', 'Artisan'],
    minOrderQty: '300 pcs per shade',
    featured: false,
    sortOrder: 6,
  },

  // ───────────────────────── Pillows / Cushions (5) ─────────────────────────
  {
    slug: 'embroidered-cotton-cushion-cover',
    name: 'Embroidered Cotton Cushion Cover',
    category: 'Pillow',
    image: '/products/pillow/1.jpg',
    shortDescription: 'Hand-embroidered cotton cushion cover with tonal threadwork — 45 × 45 cm.',
    description:
      'Cotton canvas cushion covers embellished with tonal hand embroidery — running stitch, mirror work or chain stitch depending on the design code. Each cover is finished with a concealed zip and an overlocked inner seam. A best-seller with interior stylists who want texture without loud prints.',
    benefits: [
      'Genuine hand embroidery — no two pieces identical',
      'Concealed zip with reinforced seams',
      'Tonal palette matches our rug and throw shades',
    ],
    specs: [
      { label: 'Sizes', value: '45 × 45 cm · 50 × 50 cm · 30 × 50 cm lumbar' },
      { label: 'Material', value: '100% cotton canvas, thread embroidery' },
      { label: 'Closure', value: 'Concealed YKK-style zip' },
      { label: 'Care', value: 'Dry clean recommended; gentle wash for solid shades' },
      { label: 'Insert', value: 'Cover only; feather inserts available on request' },
      { label: 'Packing', value: 'Polybag; 60 pcs per carton' },
    ],
    industries: ['Interior Studios & Designers', 'Retail & Private Label', 'Gifting & E-commerce'],
    certifications: ['OEKO-TEX', 'SEDEX'],
    tags: ['Hand embroidered', 'Best seller'],
    minOrderQty: '200 pcs per design',
    featured: true,
    sortOrder: 7,
  },
  {
    slug: 'textured-boucle-cushion',
    name: 'Textured Boucle Cushion',
    category: 'Pillow',
    image: '/products/pillow/2.jpg',
    shortDescription: 'Soft boucle-weave cushion in cream and earth tones — the quiet-luxury look.',
    description:
      'Woven in a loopy boucle yarn that reads as soft architecture on a sofa — the textured neutral that stylists keep reaching for. The cover has a linen-cotton backing for structure and a hidden zip. Colourways are curated to sit with oak, rattan and brass interiors.',
    benefits: [
      'Boucle texture with a structured linen-cotton back',
      'Curated neutral palette — cream, sand, clay, moss',
      'Shape retention even after heavy daily use',
    ],
    specs: [
      { label: 'Sizes', value: '45 × 45 cm · 50 × 50 cm' },
      { label: 'Material', value: 'Boucle face (poly-cotton); linen-cotton back' },
      { label: 'Closure', value: 'Hidden zip' },
      { label: 'Care', value: 'Dry clean; spot clean spills immediately' },
      { label: 'Colours', value: '5 neutral shades in stock' },
      { label: 'Packing', value: 'Polybag; 50 pcs per carton' },
    ],
    industries: ['Interior Studios & Designers', 'Retail & Private Label'],
    certifications: ['OEKO-TEX'],
    tags: ['Neutral'],
    minOrderQty: '200 pcs per shade',
    featured: false,
    sortOrder: 8,
  },
  {
    slug: 'jacquard-woven-cushion-cover',
    name: 'Jacquard Woven Cushion Cover',
    category: 'Pillow',
    image: '/products/pillow/3.jpg',
    shortDescription: 'Pattern woven into the fabric — geometric jacquard cushions in custom colourways.',
    description:
      'Geometric and folk motifs are woven directly into the fabric on jacquard looms, giving a two-sided, premium-feel cushion that never fades like print. We weave buyer artwork or modify our design library to a brand palette, with labdips in five working days.',
    benefits: [
      'Woven-in pattern — crisp on both faces',
      'Custom artwork woven from 300 pcs',
      'Reversible construction, two usable faces',
    ],
    specs: [
      { label: 'Sizes', value: '45 × 45 cm · 40 × 40 cm · 30 × 50 cm' },
      { label: 'Material', value: 'Cotton / poly-cotton jacquard' },
      { label: 'Closure', value: 'Concealed zip or envelope back' },
      { label: 'Care', value: 'Machine wash 30°C gentle' },
      { label: 'Customisation', value: 'Buyer artwork, up to 6 yarn colours' },
      { label: 'Packing', value: 'Polybag; 60 pcs per carton' },
    ],
    industries: ['Retail & Private Label', 'Interior Studios & Designers'],
    certifications: ['OEKO-TEX', 'ISO 9001'],
    tags: ['Custom weave'],
    minOrderQty: '300 pcs per design',
    featured: false,
    sortOrder: 9,
  },
  {
    slug: 'velvet-panel-cushion',
    name: 'Velvet Panel Cushion',
    category: 'Pillow',
    image: '/products/pillow/4.jpg',
    shortDescription: 'Deep-pile velvet front with contrast piping — jewel tones for hospitality lounges.',
    description:
      'Cut-velvet front panel stitched with contrast piping and a plain velvet back for hotels and lounges that want richness without fuss. The pile is crush-resistant and passes the abrasion and light-fastness levels expected in hospitality FF&E specifications.',
    benefits: [
      'Crush-resistant cut velvet, hospitality-grade',
      'Contrast piping in any brand colour',
      'Light-fastness grade 4+ for sunlit lobbies',
    ],
    specs: [
      { label: 'Sizes', value: '45 × 45 cm · 50 × 50 cm · 35 × 55 cm' },
      { label: 'Material', value: 'Polyester cut velvet; cotton back option' },
      { label: 'Martindale', value: '25,000+ rubs' },
      { label: 'Care', value: 'Dry clean' },
      { label: 'Colours', value: 'Emerald, rust, bordeaux, navy, mustard' },
      { label: 'Packing', value: 'Polybag; 50 pcs per carton' },
    ],
    industries: ['Hospitality & Hotels', 'Interior Studios & Designers'],
    certifications: ['OEKO-TEX'],
    tags: ['Hospitality'],
    minOrderQty: '200 pcs per colour',
    featured: false,
    sortOrder: 10,
  },
  {
    slug: 'hand-loomed-slub-cushion',
    name: 'Hand-Loomed Slub Cushion',
    category: 'Pillow',
    image: '/products/pillow/5.jpg',
    shortDescription: 'Slub-yarn handloom cushion with raw-edge detailing and natural irregularity.',
    description:
      'Woven on handlooms with irregular slub yarns, then finished with a raw-edge flange for an organic, earthy look. The deliberate irregularity is the appeal — each cover carries the hand of the weaver. Pairs naturally with our loop bath mats and flatweave dhurries.',
    benefits: [
      'Authentic handloom slub texture',
      'Raw-edge flange detailing',
      'Part of a coordinated handloom range',
    ],
    specs: [
      { label: 'Sizes', value: '45 × 45 cm · 50 × 50 cm · 30 × 50 cm' },
      { label: 'Material', value: '100% cotton slub, handloom woven' },
      { label: 'Closure', value: 'Envelope back with wooden button' },
      { label: 'Care', value: 'Gentle machine wash 30°C' },
      { label: 'Colours', value: 'Natural, oat, charcoal, terracotta' },
      { label: 'Packing', value: 'Polybag; 60 pcs per carton' },
    ],
    industries: ['Gifting & E-commerce', 'Interior Studios & Designers'],
    certifications: ['GOTS', 'SEDEX'],
    tags: ['Handloom', 'Natural'],
    minOrderQty: '200 pcs per shade',
    featured: false,
    sortOrder: 11,
  },

  // ───────────────────────── Poufs (4) ─────────────────────────
  {
    slug: 'braided-cotton-pouf',
    name: 'Braided Cotton Pouf',
    category: 'Pouf',
    image: '/products/pouf/1.jpg',
    shortDescription: 'Hand-braided cotton rope pouf — footrest, extra seat and accent piece in one.',
    description:
      'Hundreds of metres of cotton rope are hand-braided and coiled into a sculptural pouf that works as a footrest, low seat or side-table base. The dense braid holds its shape without any inner frame, and it ships with a lightweight inner core to cut freight cost.',
    benefits: [
      'Frameless dense braid keeps shape under 100 kg',
      'Ships compressed — lower freight per unit',
      'Spot-cleanable braided cotton rope',
    ],
    specs: [
      { label: 'Sizes', value: 'Ø 45 × H 35 cm · Ø 50 × H 40 cm' },
      { label: 'Material', value: 'Braided cotton rope over poly-fill core' },
      { label: 'Load', value: 'Tested to 100 kg static load' },
      { label: 'Care', value: 'Spot clean; rotate monthly' },
      { label: 'Colours', value: 'Natural, ivory, grey, bordeaux' },
      { label: 'Packing', value: '1 pc per master polybag; 8 pcs per carton' },
    ],
    industries: ['Interior Studios & Designers', 'Gifting & E-commerce', 'Hospitality & Hotels'],
    certifications: ['OEKO-TEX', 'SEDEX'],
    tags: ['Best seller', 'Hand braided'],
    minOrderQty: '150 pcs',
    featured: true,
    sortOrder: 12,
  },
  {
    slug: 'knitted-floor-pouf',
    name: 'Knitted Floor Pouf',
    category: 'Pouf',
    image: '/products/pouf/2.jpg',
    shortDescription: 'Chunky-knit cover over a firm core — cosy floor seating for lounges and kids’ rooms.',
    description:
      'A chunky hand-knit cover in thick cotton yarn zips over a firm foam-and-fibre core, giving a sink-in-but-supported floor seat. Covers are removable and washable — a practical must for family rooms and kids’ corners. Popular in nursery and playroom colourways.',
    benefits: [
      'Removable, washable knitted cover',
      'Firm foam core — sits up, does not sag',
      'Child-safe: no hard parts, no small fittings',
    ],
    specs: [
      { label: 'Sizes', value: 'Ø 50 × H 30 cm · Ø 55 × H 35 cm' },
      { label: 'Material', value: 'Hand-knit cotton cover; foam + fibre core' },
      { label: 'Core density', value: '25 kg/m³ foam blend' },
      { label: 'Care', value: 'Cover machine wash 30°C; do not tumble' },
      { label: 'Colours', value: 'Blush, mustard, teal, grey, natural' },
      { label: 'Packing', value: 'Cover and core packed nested; 6 pcs per carton' },
    ],
    industries: ['Gifting & E-commerce', 'Retail & Private Label'],
    certifications: ['OEKO-TEX'],
    tags: ['Kids friendly'],
    minOrderQty: '150 pcs',
    featured: false,
    sortOrder: 13,
  },
  {
    slug: 'patchwork-cotton-pouf',
    name: 'Patchwork Cotton Pouf',
    category: 'Pouf',
    image: '/products/pouf/3.jpg',
    shortDescription: 'Upcycled-fabric patchwork pouf — every piece one of a kind, GRS-certified content.',
    description:
      'Panel-by-panel patchwork stitched from sorted cotton offcuts and deadstock fabric, giving every pouf a unique colour story while diverting textile waste from landfill. Certified under GRS for recycled content. A natural fit for eco-forward retail and boutique hospitality.',
    benefits: [
      'Every unit visually unique',
      'GRS-certified recycled cotton content',
      'Strong sustainability story for retail floors',
    ],
    specs: [
      { label: 'Sizes', value: 'Ø 45 × H 35 cm' },
      { label: 'Material', value: 'Recycled cotton patchwork; poly-fill core' },
      { label: 'Certification', value: 'GRS chain-of-custody documentation per lot' },
      { label: 'Care', value: 'Spot clean' },
      { label: 'Colour families', value: 'Earth, jewel, neutrals (varies by lot)' },
      { label: 'Packing', value: '1 pc polybag; 8 pcs per carton' },
    ],
    industries: ['Gifting & E-commerce', 'Interior Studios & Designers'],
    certifications: ['GRS', 'SEDEX'],
    tags: ['Recycled', 'One of a kind'],
    minOrderQty: '150 pcs',
    featured: false,
    sortOrder: 14,
  },
  {
    slug: 'round-floor-cushion-pouf',
    name: 'Round Floor Cushion Pouf',
    category: 'Pouf',
    image: '/products/pouf/4.jpg',
    shortDescription: 'Flat round floor cushion with quilted top — meditation seat and lounge filler.',
    description:
      'A generously filled flat round cushion, quilted top and bottom to keep the fill evenly distributed through heavy use. Light enough to move room to room, dense enough to sit on comfortably for long stretches. Used widely in yoga studios, reading corners and majlis-style seating.',
    benefits: [
      'Quilted panels stop fill migration',
      'Lightweight — easy to re-arrange rooms',
      'Handle loop stitched into the side seam',
    ],
    specs: [
      { label: 'Sizes', value: 'Ø 55 × H 12 cm · Ø 65 × H 15 cm' },
      { label: 'Material', value: 'Cotton canvas shell; recycled poly fill' },
      { label: 'Fill', value: '2.2 – 3.0 kg per piece' },
      { label: 'Care', value: 'Spot clean; air dry flat' },
      { label: 'Colours', value: '6 shades; contrast piping on request' },
      { label: 'Packing', value: 'Vacuum-compressed; 12 pcs per carton' },
    ],
    industries: ['Hospitality & Hotels', 'Gifting & E-commerce'],
    certifications: ['OEKO-TEX', 'GRS'],
    tags: ['Floor seating'],
    minOrderQty: '200 pcs',
    featured: false,
    sortOrder: 15,
  },

  // ───────────────────────── Rugs & Carpets (9) ─────────────────────────
  {
    slug: 'hand-tufted-wool-rug',
    name: 'Hand-Tufted Wool Rug',
    category: 'Rug And Carpets',
    image: '/products/rugs/1.jpg',
    shortDescription: 'Hand-tufted New Zealand-blend wool rug with cotton canvas backing — plush and dense.',
    description:
      'Our flagship rug: premium wool blend yarn punched by hand into a canvas backing, then carved and sheared for crisp pattern edges. Dense 12 mm pile feels substantial underfoot and ships with a cotton canvas back plus anti-slip underlay recommendation. Buyer artwork is translated into tufting maps in under two weeks.',
    benefits: [
      'Hand-carved edges for crisp pattern definition',
      'Custom designs from buyer artwork — maps in 10 days',
      'Naturally soil-resistant wool blend',
    ],
    specs: [
      { label: 'Sizes', value: '120 × 180 cm · 160 × 230 cm · 200 × 300 cm · custom up to 400 cm' },
      { label: 'Material', value: 'Wool blend (70% wool / 30% viscose optional)' },
      { label: 'Pile height', value: '12 mm, hand carved' },
      { label: 'Backing', value: 'Cotton canvas with latex' },
      { label: 'Care', value: 'Professional rug cleaning; rotate periodically' },
      { label: 'Packing', value: 'Rolled, wrapped in woven sack; 1 pc per roll' },
    ],
    industries: ['Interior Studios & Designers', 'Export & Distribution', 'Hospitality & Hotels'],
    certifications: ['OEKO-TEX', 'ISO 9001'],
    tags: ['Best seller', 'Custom artwork'],
    minOrderQty: '50 pcs per design',
    featured: true,
    sortOrder: 16,
  },
  {
    slug: 'braided-jute-rug',
    name: 'Braided Jute Rug',
    category: 'Rug And Carpets',
    image: '/products/rugs/2.jpg',
    shortDescription: 'Hand-braided natural jute rug with a tonal border — texture for earthy interiors.',
    description:
      'Jute yarn is hand-braided into long ropes and coiled into round or rectangular rugs, finished with a tonal cotton border stitch. The natural fibre brings warmth and texture to earthy, coastal and boho palettes. Reversible construction doubles the working life.',
    benefits: [
      '100% natural jute — biodegradable and undyed options',
      'Reversible braid, two usable faces',
      'Round, oval and rectangular shapes from one line',
    ],
    specs: [
      { label: 'Sizes', value: 'Ø 120 cm · 90 × 150 cm · 120 × 180 cm · 160 × 230 cm' },
      { label: 'Material', value: '100% jute braid, cotton border stitch' },
      { label: 'Thickness', value: '8 – 10 mm' },
      { label: 'Shapes', value: 'Round, oval, rectangle, runner' },
      { label: 'Care', value: 'Shake out, vacuum without beater bar; spot clean' },
      { label: 'Packing', value: 'Folded flat; 10 pcs per bale' },
    ],
    industries: ['Export & Distribution', 'Retail & Private Label', 'Interior Studios & Designers'],
    certifications: ['SEDEX'],
    tags: ['Natural fibre', 'Reversible'],
    minOrderQty: '100 pcs per size',
    featured: false,
    sortOrder: 17,
  },
  {
    slug: 'flatweave-cotton-dhurrie',
    name: 'Flatweave Cotton Dhurrie',
    category: 'Rug And Carpets',
    image: '/products/rugs/3.jpg',
    shortDescription: 'Reversible handwoven cotton dhurrie — light, washable and easy to ship.',
    description:
      'The classic Indian flatweave, hand-woven on panja looms in bold or tonal patterns. At 4–5 mm it slides under doors, folds for freight efficiency and can be machine washed in domestic sizes — a practical first rug for e-commerce buyers. Every dhurrie is fully reversible.',
    benefits: [
      'Fully reversible flatweave',
      'Folds flat — lowest shipping volume of any rug type',
      'Washable in domestic sizes',
    ],
    specs: [
      { label: 'Sizes', value: '90 × 150 cm · 120 × 180 cm · 150 × 240 cm · 60 × 200 cm runner' },
      { label: 'Material', value: '100% cotton, panja-loom flatweave' },
      { label: 'Thickness', value: '4 – 5 mm' },
      { label: 'Care', value: 'Machine wash cold for domestic sizes; line dry flat' },
      { label: 'Patterns', value: 'Stripes, geometric, tonal; custom palettes from 100 pcs' },
      { label: 'Packing', value: 'Folded and banded; 20 pcs per bale' },
    ],
    industries: ['Export & Distribution', 'Gifting & E-commerce', 'Retail & Private Label'],
    certifications: ['OEKO-TEX', 'GOTS'],
    tags: ['Handwoven', 'Reversible'],
    minOrderQty: '100 pcs per design',
    featured: true,
    sortOrder: 18,
  },
  {
    slug: 'shaggy-polyester-rug',
    name: 'Shaggy Polyester Rug',
    category: 'Rug And Carpets',
    image: '/products/rugs/4.jpg',
    shortDescription: 'Deep 40 mm shaggy pile with non-shed fibres — the volume retail line.',
    description:
      'Machine-made deep-pile shaggy in fine polyester microfibre, engineered to resist shedding — the number-one complaint in the shaggy category. Non-slip cotton back with latex dots, colourfast to sunlight, and priced for volume retail programmes. Custom sizes run on the same loom set.',
    benefits: [
      'Non-shed microfibre pile, tested over 10 wash cycles',
      'Non-slip latex-dotted backing',
      'Volume pricing with consistent loom quality',
    ],
    specs: [
      { label: 'Sizes', value: '120 × 170 cm · 160 × 230 cm · 200 × 290 cm · runners' },
      { label: 'Material', value: '100% polyester microfibre pile' },
      { label: 'Pile height', value: '40 mm' },
      { label: 'Backing', value: 'Cotton with latex anti-slip dots' },
      { label: 'Care', value: 'Vacuum regularly; spot clean' },
      { label: 'Packing', value: 'Rolled in poly; 1 pc per roll' },
    ],
    industries: ['Retail & Private Label', 'Export & Distribution'],
    certifications: ['OEKO-TEX', 'REACH'],
    tags: ['Volume', 'Non-shed'],
    minOrderQty: '100 pcs per size',
    featured: false,
    sortOrder: 19,
  },
  {
    slug: 'hand-woven-wool-blend-rug',
    name: 'Hand-Woven Wool Blend Rug',
    category: 'Rug And Carpets',
    image: '/products/rugs/5.jpg',
    shortDescription: 'Hand-woven wool-and-cotton rug with tonal geometries — designer-grade finish.',
    description:
      'Woven by hand in wool blended with cotton warp, producing a low, dense pile that sits beautifully in dining and living rooms. Tonal geometries are woven to our design library or to buyer palettes, with labdips in five working days. Each rug carries the subtle irregularity of genuine handwork.',
    benefits: [
      'Genuine handloom weave with designer-grade finish',
      'Low pile fits under doors and dining tables',
      'Buyer palettes from 60 pcs',
    ],
    specs: [
      { label: 'Sizes', value: '120 × 180 cm · 150 × 230 cm · 170 × 240 cm · 200 × 300 cm' },
      { label: 'Material', value: '60% wool / 40% cotton' },
      { label: 'Thickness', value: '6 – 8 mm' },
      { label: 'Care', value: 'Professional cleaning recommended' },
      { label: 'Colours', value: 'Tonal earth, indigo, charcoal, ivory' },
      { label: 'Packing', value: 'Rolled in woven sack; 1 pc per roll' },
    ],
    industries: ['Interior Studios & Designers', 'Export & Distribution'],
    certifications: ['OEKO-TEX', 'SEDEX'],
    tags: ['Handwoven', 'Designer'],
    minOrderQty: '60 pcs per design',
    featured: false,
    sortOrder: 20,
  },
  {
    slug: 'printed-cotton-area-rug',
    name: 'Printed Cotton Area Rug',
    category: 'Rug And Carpets',
    image: '/products/rugs/6.jpg',
    shortDescription: 'Brushed cotton rug with high-definition print and anti-slip back — fast-moving retail.',
    description:
      'Brushed cotton canvas printed with high-definition motifs, then backed with a latex anti-slip coat. Print quality holds 90%+ of original density after ten washes. The light weight makes it an easy parcel-size e-commerce product, and new prints can be sampled within seven days.',
    benefits: [
      'High-definition print, colourfast after washing',
      'Parcel-friendly weight for e-commerce',
      'New print sampling in 7 days',
    ],
    specs: [
      { label: 'Sizes', value: '90 × 150 cm · 120 × 180 cm · 160 × 230 cm' },
      { label: 'Material', value: 'Brushed cotton with latex back' },
      { label: 'Weight', value: '1,600 – 2,000 GSM' },
      { label: 'Care', value: 'Machine wash cold, gentle; line dry' },
      { label: 'Prints', value: 'Library of 40+ motifs; custom artwork from 200 pcs' },
      { label: 'Packing', value: 'Folded polybag; 15 pcs per carton' },
    ],
    industries: ['Gifting & E-commerce', 'Retail & Private Label'],
    certifications: ['OEKO-TEX'],
    tags: ['E-commerce', 'Printed'],
    minOrderQty: '200 pcs per print',
    featured: false,
    sortOrder: 21,
  },
  {
    slug: 'hand-carved-wool-rug',
    name: 'Hand-Carved Wool Rug',
    category: 'Rug And Carpets',
    image: '/products/rugs/7.jpg',
    shortDescription: 'Sculptural 3D-effect pile, carved by hand — statement rugs for feature rooms.',
    description:
      'Tufted at varying pile heights and then hand-carved along every contour, this rug creates a dimensional, relief-like surface that catches light and shadow. The carving stage is entirely manual — our carvers follow the design map line by line. Best suited to bedrooms, lounges and boutique lobbies where the rug is the statement.',
    benefits: [
      'True 3D carving — multiple pile levels per rug',
      'Fully manual carving for crisp sculpted edges',
      'Statement scale up to 300 × 400 cm',
    ],
    specs: [
      { label: 'Sizes', value: '150 × 230 cm · 170 × 240 cm · 200 × 300 cm · custom' },
      { label: 'Material', value: 'Wool with viscose accent yarns' },
      { label: 'Pile height', value: '8 – 20 mm multi-level carving' },
      { label: 'Backing', value: 'Cotton canvas with latex' },
      { label: 'Care', value: 'Professional rug cleaning; no beater vacuum' },
      { label: 'Packing', value: 'Rolled with scuff-guard wrap; 1 pc per roll' },
    ],
    industries: ['Interior Studios & Designers', 'Hospitality & Hotels'],
    certifications: ['OEKO-TEX', 'ISO 9001'],
    tags: ['Hand carved', 'Statement'],
    minOrderQty: '40 pcs per design',
    featured: false,
    sortOrder: 22,
  },
  {
    slug: 'cotton-punch-embroidery-rug',
    name: 'Cotton Punch Rug',
    category: 'Rug And Carpets',
    image: '/products/rugs/8.jpg',
    shortDescription: 'Punch-needle cotton rug with dense stitched motifs — handmade character, soft handle.',
    description:
      'Punch-needle work pushes thick cotton yarn through a monks-cloth foundation, building raised loops that form dense, folk-inspired motifs. The technique gives a chunky, handmade surface that stays flexible and comfortable underfoot. Sizes are flexible because panels are stitched and joined by hand.',
    benefits: [
      'Genuine punch-needle handwork, motif per motif',
      'Flexible, soft surface — comfortable underfoot',
      'Round and shaped silhouettes possible',
    ],
    specs: [
      { label: 'Sizes', value: 'Ø 120 cm · Ø 150 cm · 90 × 150 cm · 120 × 180 cm' },
      { label: 'Material', value: '100% cotton yarn on monks-cloth base' },
      { label: 'Loop height', value: '6 – 8 mm' },
      { label: 'Backing', value: 'Anti-slip fabric backing stitched on' },
      { label: 'Care', value: 'Spot clean; gentle hand wash for domestic sizes' },
      { label: 'Packing', value: 'Folded polybag; 12 pcs per carton' },
    ],
    industries: ['Gifting & E-commerce', 'Interior Studios & Designers'],
    certifications: ['OEKO-TEX', 'SEDEX'],
    tags: ['Handmade', 'Folk motifs'],
    minOrderQty: '100 pcs per design',
    featured: false,
    sortOrder: 23,
  },
  {
    slug: 'washable-printed-runner',
    name: 'Washable Printed Runner',
    category: 'Rug And Carpets',
    image: '/products/rugs/9.jpg',
    shortDescription: 'Slim machine-washable runners for kitchens, hallways and vanities — busy-home proof.',
    description:
      'A flat-woven, low-profile runner engineered for the messiest lanes of the house — kitchens, hallways and bathroom vanities. It machine-washes at 30°C without fraying or fading, thanks to locked-edge binding and fibre-bonded print. The thin 4 mm profile clears door swings and lies flat immediately after unrolling.',
    benefits: [
      'Machine washable — spills are no drama',
      '4 mm profile clears doors and lies flat fast',
      'Locked edges never fray or curl',
    ],
    specs: [
      { label: 'Sizes', value: '60 × 200 cm · 60 × 300 cm · 80 × 300 cm · custom lengths' },
      { label: 'Material', value: 'Poly-cotton flatweave, bonded print' },
      { label: 'Thickness', value: '4 mm' },
      { label: 'Backing', value: 'Latex anti-slip coat' },
      { label: 'Care', value: 'Machine wash 30°C, no bleach; line dry flat' },
      { label: 'Packing', value: 'Rolled in poly; 20 pcs per carton' },
    ],
    industries: ['Retail & Private Label', 'Gifting & E-commerce'],
    certifications: ['OEKO-TEX'],
    tags: ['Washable', 'Runner'],
    minOrderQty: '200 pcs per print',
    featured: false,
    sortOrder: 24,
  },

  // ───────────────────────── Throws (19) ─────────────────────────
  {
    slug: 'waffle-weave-cotton-throw',
    name: 'Waffle Weave Cotton Throw',
    category: 'Throw',
    image: '/products/throw/1.jpg',
    shortDescription: 'Breathable waffle throw with self-fringe — the everyday sofa layer.',
    description:
      'A crisp waffle-weave throw in 100% cotton that adds texture without weight — the layer that stays on the sofa year-round. Self-fringe ends are woven in, not stitched on, so they never unravel. Breathable enough for summer evenings and warm enough layered in winter.',
    benefits: [
      'Woven-in self-fringe that never unravels',
      'Breathable four-season weight',
      'Softens further with every wash',
    ],
    specs: [
      { label: 'Sizes', value: '125 × 150 cm · 130 × 170 cm' },
      { label: 'Material', value: '100% cotton waffle weave' },
      { label: 'Weight', value: '380 – 450 GSM' },
      { label: 'Care', value: 'Machine wash 30°C; low tumble' },
      { label: 'Colours', value: '10 stock shades' },
      { label: 'Packing', value: 'Polybag; 40 pcs per carton' },
    ],
    industries: ['Retail & Private Label', 'Gifting & E-commerce', 'Hospitality & Hotels'],
    certifications: ['OEKO-TEX'],
    tags: ['Best seller', 'Four season'],
    minOrderQty: '300 pcs per shade',
    featured: true,
    sortOrder: 25,
  },
  {
    slug: 'fringed-herringbone-throw',
    name: 'Fringed Herringbone Throw',
    category: 'Throw',
    image: '/products/throw/2.jpg',
    shortDescription: 'Classic herringbone weave with hand-knotted fringe — a quiet, tailored drape.',
    description:
      'Woven in a fine herringbone twill with hand-knotted fringe, this throw reads tailored rather than rustic. The twill structure gives a subtle sheen and excellent drape over sofa arms and bed footends. A dependable private-label shape that retails across price tiers simply by changing the yarn.',
    benefits: [
      'Hand-knotted fringe, individually finished',
      'Excellent drape from twill structure',
      'Same shape, three yarn tiers for tiered retail pricing',
    ],
    specs: [
      { label: 'Sizes', value: '127 × 152 cm · 130 × 180 cm' },
      { label: 'Material', value: 'Cotton, cotton-acrylic or merino-blend tiers' },
      { label: 'Weight', value: '500 – 700 GSM' },
      { label: 'Care', value: 'Gentle wash 30°C or dry clean' },
      { label: 'Colours', value: '14 stock colourways' },
      { label: 'Packing', value: 'Polybag with printed band; 30 pcs per carton' },
    ],
    industries: ['Retail & Private Label', 'Hospitality & Hotels'],
    certifications: ['OEKO-TEX', 'ISO 9001'],
    tags: ['Private label'],
    minOrderQty: '300 pcs per colourway',
    featured: false,
    sortOrder: 26,
  },
  {
    slug: 'chunky-knit-throw',
    name: 'Chunky Knit Throw',
    category: 'Throw',
    image: '/products/throw/3.jpg',
    shortDescription: 'Oversized hand-knit throw in thick cotton yarn — maximum cosy factor.',
    description:
      'Hand-knitted in oversized stitches from thick cotton tube yarn, this is the throw that photographs beautifully and gets stolen by everyone in the house. Generous 130 × 170 cm coverage, with a weight that feels like an embrace. Cotton yarn means it breathes and never itches.',
    benefits: [
      'Oversized stitch definition for retail display',
      'Cotton tube yarn — warm but breathable',
      'Hand-knit by our artisan partner network',
    ],
    specs: [
      { label: 'Sizes', value: '130 × 170 cm · 150 × 200 cm' },
      { label: 'Material', value: '100% cotton tube yarn, hand knit' },
      { label: 'Weight', value: '1.4 – 2.0 kg per piece' },
      { label: 'Care', value: 'Gentle wash 30°C, dry flat' },
      { label: 'Colours', value: 'Cream, camel, charcoal, blush, sage' },
      { label: 'Packing', value: 'Folded in cloth bag; 12 pcs per carton' },
    ],
    industries: ['Gifting & E-commerce', 'Retail & Private Label'],
    certifications: ['OEKO-TEX'],
    tags: ['Hand knit', 'Gifting'],
    minOrderQty: '200 pcs per shade',
    featured: false,
    sortOrder: 27,
  },
  {
    slug: 'recycled-poly-sherpa-throw',
    name: 'Recycled Poly Sherpa Throw',
    category: 'Throw',
    image: '/products/throw/4.jpg',
    shortDescription: 'GRS-certified rPET sherpa throw — teddy-soft face with a smooth quilted back.',
    description:
      'Teddy-soft sherpa face knitted from certified recycled polyester (GRS), bonded to a smooth quilted reverse. Warmth-to-weight is exceptional, and the fibre does not shed onto dark sofas. Each throw carries GRS transaction-certificate documentation for the buyer’s compliance file.',
    benefits: [
      'GRS-certified recycled content with transaction certificates',
      'Non-shed sherpa face, quilted smooth back',
      'Exceptional warmth at under 1 kg weight',
    ],
    specs: [
      { label: 'Sizes', value: '130 × 170 cm · 150 × 200 cm' },
      { label: 'Material', value: '100% recycled polyester (GRS)' },
      { label: 'Weight', value: '700 – 900 GSM' },
      { label: 'Care', value: 'Machine wash 30°C; low tumble' },
      { label: 'Colours', value: 'Ivory, taupe, grey, bordeaux' },
      { label: 'Packing', value: 'Polybag; 20 pcs per carton' },
    ],
    industries: ['Retail & Private Label', 'Export & Distribution'],
    certifications: ['GRS', 'REACH'],
    tags: ['Recycled', 'Cosy'],
    minOrderQty: '300 pcs per shade',
    featured: false,
    sortOrder: 28,
  },
  {
    slug: 'handloom-cotton-throw',
    name: 'Handloom Cotton Throw',
    category: 'Throw',
    image: '/products/throw/5.jpg',
    shortDescription: 'Artisan handloom throw with khadi texture and hand-twisted tassels.',
    description:
      'Woven on village handlooms in a loose khadi-style weave, then finished with hand-twisted tassels. The open texture is airy in summer and layers well in winter, and every purchase supports our partner weaver clusters. GOTS-organic yarn available for eco programmes.',
    benefits: [
      'Authentic khadi-style handloom texture',
      'Hand-twisted tassel finish',
      'GOTS organic yarn option',
    ],
    specs: [
      { label: 'Sizes', value: '125 × 150 cm · 130 × 180 cm' },
      { label: 'Material', value: '100% cotton handloom (GOTS option)' },
      { label: 'Weight', value: '350 – 420 GSM' },
      { label: 'Care', value: 'Gentle wash 30°C; expect softening' },
      { label: 'Colours', value: 'Naturals and muted tones; custom from 200 pcs' },
      { label: 'Packing', value: 'Folded with kraft band; 30 pcs per carton' },
    ],
    industries: ['Gifting & E-commerce', 'Interior Studios & Designers'],
    certifications: ['GOTS', 'SEDEX'],
    tags: ['Artisan', 'Organic option'],
    minOrderQty: '200 pcs',
    featured: false,
    sortOrder: 29,
  },
  {
    slug: 'brushed-mohair-blend-throw',
    name: 'Brushed Mohair-Blend Throw',
    category: 'Throw',
    image: '/products/throw/6.jpg',
    shortDescription: 'Brushed mohair-blend throw with a halo softness — the premium gifting piece.',
    description:
      'Our softest throw: a mohair-blend weave brushed on both faces to raise a fine halo of fibre that feels weightless and warm. Presented in a reusable cotton tote for gifting shelves. Low-lint brushing keeps dark sofas clean, and pilling performance is tested to four wash cycles.',
    benefits: [
      'Double-faced brushing for halo softness',
      'Anti-pill tested over four wash cycles',
      'Reusable cotton tote packaging for gifting',
    ],
    specs: [
      { label: 'Sizes', value: '130 × 180 cm' },
      { label: 'Material', value: 'Mohair blend (30% mohair / 70% fine acrylic)' },
      { label: 'Weight', value: '600 – 750 GSM' },
      { label: 'Care', value: 'Hand wash cool or dry clean' },
      { label: 'Colours', value: '6 jewel and neutral tones' },
      { label: 'Packing', value: 'Cotton tote + insert card; 20 pcs per carton' },
    ],
    industries: ['Gifting & E-commerce', 'Retail & Private Label'],
    certifications: ['OEKO-TEX', 'REACH'],
    tags: ['Premium', 'Gifting'],
    minOrderQty: '200 pcs per shade',
    featured: false,
    sortOrder: 30,
  },
  {
    slug: 'herringbone-wool-throw',
    name: 'Herringbone Wool Throw',
    category: 'Throw',
    image: '/products/throw/7.jpg',
    shortDescription: 'Lambswool herringbone throw with dry handle and blanket-stitch edging.',
    description:
      'A proper winter throw in lambswool, woven in a tight herringbone and finished with a tonal blanket-stitch edge. The wool is lightly brushed for a dry, smooth handle — warm without the itch associated with coarser wools. Scottish-heritage colourways adapted for contemporary interiors.',
    benefits: [
      'Lambswool warmth with a smooth, non-itch finish',
      'Blanket-stitch edge in tonal yarn',
      'Naturally temperature-regulating and odour-resistant',
    ],
    specs: [
      { label: 'Sizes', value: '130 × 180 cm · 150 × 200 cm' },
      { label: 'Material', value: '100% lambswool' },
      { label: 'Weight', value: '700 – 850 GSM' },
      { label: 'Care', value: 'Dry clean or airing wash per care label' },
      { label: 'Colours', value: 'Check, plaid and solid heritage tones' },
      { label: 'Packing', value: 'Folded with belly band; 20 pcs per carton' },
    ],
    industries: ['Retail & Private Label', 'Export & Distribution'],
    certifications: ['OEKO-TEX', 'ISO 9001'],
    tags: ['Wool', 'Winter'],
    minOrderQty: '200 pcs per colourway',
    featured: false,
    sortOrder: 31,
  },
  {
    slug: 'stripe-woven-throw',
    name: 'Stripe Woven Throw',
    category: 'Throw',
    image: '/products/throw/8.jpg',
    shortDescription: 'Multi-stripe cotton throw with contrast ends — easy colour for sofas and beds.',
    description:
      'A cheerful multi-stripe throw woven in yarn-dyed cotton, where stripes run through the full body and the ends carry a solid contrast band. Yarn-dyeing (not printing) keeps stripes crisp on both faces. An easy, colourful layer that retails well across seasons and pairs with plain cushions.',
    benefits: [
      'Yarn-dyed stripes — crisp on both faces',
      'Contrast end band ties the palette together',
      'Coordinates with our striped dhurries',
    ],
    specs: [
      { label: 'Sizes', value: '127 × 152 cm · 130 × 180 cm' },
      { label: 'Material', value: '100% yarn-dyed cotton' },
      { label: 'Weight', value: '450 – 550 GSM' },
      { label: 'Care', value: 'Machine wash 30°C' },
      { label: 'Stripes', value: '12 stock stripe palettes; custom from 300 pcs' },
      { label: 'Packing', value: 'Polybag; 40 pcs per carton' },
    ],
    industries: ['Retail & Private Label', 'Gifting & E-commerce'],
    certifications: ['OEKO-TEX'],
    tags: ['Stripes', 'Colour'],
    minOrderQty: '300 pcs per palette',
    featured: false,
    sortOrder: 32,
  },
  {
    slug: 'boucle-texture-throw',
    name: 'Boucle Texture Throw',
    category: 'Throw',
    image: '/products/throw/9.jpg',
    shortDescription: 'Looped boucle throw with a cloud-like surface — texture on texture styling.',
    description:
      'Woven with loopy boucle yarn across the full surface, giving a cloud-soft, nubby texture that photographs beautifully and feels even better. The open structure keeps it breathable while the twisted fringe ends add a relaxed finish. The natural companion to our boucle cushions.',
    benefits: [
      'Full-surface boucle loops — plush but breathable',
      'Twisted fringe ends',
      'Matches our boucle cushion programme',
    ],
    specs: [
      { label: 'Sizes', value: '130 × 170 cm · 150 × 200 cm' },
      { label: 'Material', value: 'Boucle poly-cotton with cotton back' },
      { label: 'Weight', value: '600 – 750 GSM' },
      { label: 'Care', value: 'Gentle wash 30°C; do not tumble' },
      { label: 'Colours', value: 'Cream, oat, cloud grey, sage, clay' },
      { label: 'Packing', value: 'Polybag; 25 pcs per carton' },
    ],
    industries: ['Interior Studios & Designers', 'Retail & Private Label'],
    certifications: ['OEKO-TEX'],
    tags: ['Texture', 'Neutral'],
    minOrderQty: '200 pcs per shade',
    featured: false,
    sortOrder: 33,
  },
  {
    slug: 'quilted-cotton-throw',
    name: 'Quilted Cotton Throw',
    category: 'Throw',
    image: '/products/throw/10.jpg',
    shortDescription: 'Two-layer quilted throw with running-stitch pattern — light warmth, everyday use.',
    description:
      'Two cotton layers are quilted together with a running-stitch diamond pattern, trapping a whisper of fill for light, even warmth. Lighter than a comforter and sturdier than a flatweave, it is the throw that lives on the family sofa. Pre-washed fabric means minimal shrinkage and immediate softness.',
    benefits: [
      'Pre-washed — no first-wash shrinkage',
      'Even fill distribution from diamond quilting',
      'Machine washable at home',
    ],
    specs: [
      { label: 'Sizes', value: '130 × 170 cm · 150 × 200 cm · 220 × 240 cm coverlet size' },
      { label: 'Material', value: '100% cotton shell; cotton-rich fill' },
      { label: 'Weight', value: '800 – 1,000 GSM' },
      { label: 'Care', value: 'Machine wash 30°C; low tumble' },
      { label: 'Colours', value: '8 solids; reverse in tonal shade' },
      { label: 'Packing', value: 'Polybag; 15 pcs per carton' },
    ],
    industries: ['Retail & Private Label', 'Hospitality & Hotels'],
    certifications: ['OEKO-TEX'],
    tags: ['Quilted', 'Everyday'],
    minOrderQty: '300 pcs per shade',
    featured: false,
    sortOrder: 34,
  },
  {
    slug: 'chenille-bedspread-throw',
    name: 'Chenille Bedspread Throw',
    category: 'Throw',
    image: '/products/throw/11.jpg',
    shortDescription: 'Vintage-style chenille bedspread throw with raised tufted motifs.',
    description:
      'A revival of the classic tufted chenille bedspread: raised chenille motifs are woven across a crisp cotton ground, creating a plush, sculpted surface with unmistakable vintage charm. Popular for heritage hotels, cottage-core retail and anyone who wants a bed to feel like a hug.',
    benefits: [
      'Raised chenille tufting with retro charm',
      'Crisp cotton ground keeps the drape tidy',
      'Strong retail story for heritage and cottage looks',
    ],
    specs: [
      { label: 'Sizes', value: '130 × 180 cm · 150 × 200 cm · 220 × 240 cm bedspread' },
      { label: 'Material', value: 'Cotton ground with chenille tufting' },
      { label: 'Weight', value: '900 – 1,100 GSM' },
      { label: 'Care', value: 'Gentle wash 30°C; no tumble' },
      { label: 'Motifs', value: 'Floral, geometric and medallion library' },
      { label: 'Packing', value: 'Folded polybag; 12 pcs per carton' },
    ],
    industries: ['Hospitality & Hotels', 'Retail & Private Label'],
    certifications: ['OEKO-TEX'],
    tags: ['Vintage', 'Tufted'],
    minOrderQty: '200 pcs per design',
    featured: false,
    sortOrder: 35,
  },
  {
    slug: 'canvas-bed-end-throw',
    name: 'Canvas Bed-End Throw',
    category: 'Throw',
    image: '/products/throw/12.jpg',
    shortDescription: 'Structured cotton-canvas bed-end throw with contrast whipstitch border.',
    description:
      'A heavier, structured throw designed to lie flat across the foot of a bed — hotel-style dressing with a tailored contrast whipstitch border. The canvas-weight cotton holds its line without constant straightening by housekeeping, which is exactly why hotel buyers specify it.',
    benefits: [
      'Structured drape that stays put on the bed',
      'Contrast whipstitch border detail',
      'Housekeeping-friendly — smooths in seconds',
    ],
    specs: [
      { label: 'Sizes', value: '150 × 200 cm · 220 × 240 cm' },
      { label: 'Material', value: '100% cotton canvas' },
      { label: 'Weight', value: '1,000 – 1,200 GSM' },
      { label: 'Care', value: 'Machine wash 40°C; iron face side' },
      { label: 'Colours', value: 'Neutrals with 6 border colours' },
      { label: 'Packing', value: 'Folded polybag; 10 pcs per carton' },
    ],
    industries: ['Hospitality & Hotels', 'Interior Studios & Designers'],
    certifications: ['OEKO-TEX', 'SEDEX'],
    tags: ['Hospitality', 'Bed end'],
    minOrderQty: '200 pcs per colourway',
    featured: false,
    sortOrder: 36,
  },
  {
    slug: 'cable-knit-throw',
    name: 'Cable Knit Throw',
    category: 'Throw',
    image: '/products/throw/13.jpg',
    shortDescription: 'Traditional cable-knit throw in soft acrylic-cotton — cabin-warmth for winter drops.',
    description:
      'The beloved fisherman cable pattern, knitted in a soft acrylic-cotton blend that keeps the look of wool without the itch or the weight. Deep cable ridges trap air for real warmth, and the blend machine-washes without felting. A reliable autumn/winter retail anchor.',
    benefits: [
      'Wool look without wool itch or weight',
      'Deep cable ridges trap warmth',
      'Machine washable — no felting',
    ],
    specs: [
      { label: 'Sizes', value: '130 × 170 cm · 150 × 200 cm' },
      { label: 'Material', value: 'Acrylic-cotton blend knit' },
      { label: 'Weight', value: '1.1 – 1.5 kg per piece' },
      { label: 'Care', value: 'Machine wash 30°C; dry flat' },
      { label: 'Colours', value: 'Cream, oat, camel, slate, forest' },
      { label: 'Packing', value: 'Polybag; 15 pcs per carton' },
    ],
    industries: ['Retail & Private Label', 'Gifting & E-commerce'],
    certifications: ['OEKO-TEX'],
    tags: ['Cable knit', 'Winter'],
    minOrderQty: '200 pcs per shade',
    featured: false,
    sortOrder: 37,
  },
  {
    slug: 'pom-pom-trim-throw',
    name: 'Pom-Pom Trim Throw',
    category: 'Throw',
    image: '/products/throw/14.jpg',
    shortDescription: 'Flatweave cotton throw edged with hand-tied pom-poms — playful and photogenic.',
    description:
      'A soft flatweave base finished with hand-tied pom-poms along all four edges — the detail that makes this throw a social-media favourite and a gift-shop bestseller. Poms are knotted individually so they stay attached through washing. Light, foldable and endlessly giftable.',
    benefits: [
      'Hand-tied pom-poms on all four edges',
      'Poms stay attached through wash cycles',
      'Gift-shop favourite with strong margin',
    ],
    specs: [
      { label: 'Sizes', value: '125 × 150 cm · 130 × 180 cm' },
      { label: 'Material', value: '100% cotton flatweave; cotton poms' },
      { label: 'Weight', value: '400 – 500 GSM' },
      { label: 'Care', value: 'Gentle wash 30°C in laundry bag' },
      { label: 'Colours', value: '8 body shades × 4 pom colours' },
      { label: 'Packing', value: 'Polybag; 30 pcs per carton' },
    ],
    industries: ['Gifting & E-commerce', 'Retail & Private Label'],
    certifications: ['OEKO-TEX'],
    tags: ['Pom-pom', 'Gifting'],
    minOrderQty: '300 pcs per colourway',
    featured: false,
    sortOrder: 38,
  },
  {
    slug: 'printed-canvas-throw',
    name: 'Printed Canvas Throw',
    category: 'Throw',
    image: '/products/throw/15.jpg',
    shortDescription: 'Statement-print cotton canvas throw with fringe — a bold layer for plain sofas.',
    description:
      'For buyers who want the throw to be the loudest thing in the room: bold botanical, geometric or folk prints on mid-weight cotton canvas, finished with a raw fringe. Reactive dyes keep the print bold through washing. Great for capsule drops and seasonal collections.',
    benefits: [
      'Bold reactive-dye prints that survive washing',
      'Raw fringe finish with a relaxed look',
      'New print sampling in 7 days',
    ],
    specs: [
      { label: 'Sizes', value: '130 × 170 cm · 150 × 200 cm' },
      { label: 'Material', value: '100% cotton canvas, reactive print' },
      { label: 'Weight', value: '650 – 800 GSM' },
      { label: 'Care', value: 'Machine wash 30°C; line dry' },
      { label: 'Prints', value: '25+ print library; custom artwork from 200 pcs' },
      { label: 'Packing', value: 'Polybag; 25 pcs per carton' },
    ],
    industries: ['Retail & Private Label', 'Gifting & E-commerce'],
    certifications: ['OEKO-TEX'],
    tags: ['Printed', 'Statement'],
    minOrderQty: '200 pcs per print',
    featured: false,
    sortOrder: 39,
  },
  {
    slug: 'brushed-flannel-throw',
    name: 'Brushed Flannel Throw',
    category: 'Throw',
    image: '/products/throw/16.jpg',
    shortDescription: 'Double-brushed flannel throw — featherweight warmth with a peachy hand-feel.',
    description:
      'Cotton flannel brushed on both faces to a peachy softness, giving surprising warmth at a featherweight. Ideal for nurseries, travel packs and summer-to-winter transition ranges. Yarn-dyed checks and prints keep their definition because both faces are brushed evenly.',
    benefits: [
      'Double-brushed peachy softness',
      'Big warmth at very low weight',
      'Nursery-safe, OEKO-TEX Class I option',
    ],
    specs: [
      { label: 'Sizes', value: '110 × 140 cm · 130 × 170 cm' },
      { label: 'Material', value: '100% brushed cotton flannel' },
      { label: 'Weight', value: '280 – 360 GSM' },
      { label: 'Care', value: 'Machine wash 30°C; low tumble' },
      { label: 'Designs', value: 'Checks, stars, florals — 15 stock designs' },
      { label: 'Packing', value: 'Polybag with printed band; 40 pcs per carton' },
    ],
    industries: ['Gifting & E-commerce', 'Retail & Private Label'],
    certifications: ['OEKO-TEX'],
    tags: ['Flannel', 'Featherweight'],
    minOrderQty: '300 pcs per design',
    featured: false,
    sortOrder: 40,
  },
  {
    slug: 'denim-patch-throw',
    name: 'Denim Patch Throw',
    category: 'Throw',
    image: '/products/throw/17.jpg',
    shortDescription: 'Upcycled denim patchwork throw — every piece unique with visible mend details.',
    description:
      'Panel-by-panel patchwork of sorted post-consumer and deadstock denim, joined with visible topstitching and occasional Japanese boro-style mend details. Each throw is one of a kind, with its own shade map. Certified under GRS for recycled content — a talking piece for eco-conscious retail.',
    benefits: [
      'One of a kind — every unit has a unique patch map',
      'GRS-certified recycled denim content',
      'Boro-style mends add authentic character',
    ],
    specs: [
      { label: 'Sizes', value: '130 × 170 cm · 150 × 200 cm' },
      { label: 'Material', value: 'Recycled denim patchwork; cotton back' },
      { label: 'Weight', value: '900 – 1,100 GSM' },
      { label: 'Certification', value: 'GRS chain-of-custody per lot' },
      { label: 'Care', value: 'Machine wash cold; line dry' },
      { label: 'Packing', value: 'Folded with kraft band; 15 pcs per carton' },
    ],
    industries: ['Gifting & E-commerce', 'Interior Studios & Designers'],
    certifications: ['GRS', 'SEDEX'],
    tags: ['Upcycled', 'One of a kind'],
    minOrderQty: '150 pcs',
    featured: false,
    sortOrder: 41,
  },
  {
    slug: 'two-tone-reversible-throw',
    name: 'Two-Tone Reversible Throw',
    category: 'Throw',
    image: '/products/throw/18.jpg',
    shortDescription: 'Double-faced throw in two solid shades — two looks in one, housekeeping-approved.',
    description:
      'Two solid-colour faces are woven as one fabric, so flipping the throw swaps the room’s accent colour instantly. No print, no fuss — just clean, hotel-grade colour blocking. Buyers use it to give one SKU two merchandising looks across a season.',
    benefits: [
      'Two usable faces — two colour looks per SKU',
      'Woven double-face, not stitched panels',
      'Ideal neutral layering for hotel bedding',
    ],
    specs: [
      { label: 'Sizes', value: '130 × 180 cm · 150 × 200 cm' },
      { label: 'Material', value: '100% cotton double-face weave' },
      { label: 'Weight', value: '550 – 700 GSM' },
      { label: 'Care', value: 'Machine wash 30°C' },
      { label: 'Combinations', value: '10 stock pairs; custom pairs from 300 pcs' },
      { label: 'Packing', value: 'Polybag; 30 pcs per carton' },
    ],
    industries: ['Hospitality & Hotels', 'Retail & Private Label'],
    certifications: ['OEKO-TEX', 'ISO 9001'],
    tags: ['Reversible', 'Colour block'],
    minOrderQty: '300 pcs per pair',
    featured: false,
    sortOrder: 42,
  },
  {
    slug: 'metallic-thread-throw',
    name: 'Metallic Thread Throw',
    category: 'Throw',
    image: '/products/throw/19.jpg',
    shortDescription: 'Cotton throw laced with a fine metallic yarn — festive shimmer for gifting season.',
    description:
      'A fine metallic yarn is woven through soft cotton in subtle stripes and checks, giving a restrained shimmer that reads festive, not flashy. Developed for the Diwali-to-Christmas gifting window and hotel festive turndown programmes. Shimmer stays bright through repeated gentle washing.',
    benefits: [
      'Restrained festive shimmer woven in',
      'Cotton-soft hand-feel, no scratch',
      'Turndown-programme friendly sizing',
    ],
    specs: [
      { label: 'Sizes', value: '130 × 170 cm · 150 × 200 cm' },
      { label: 'Material', value: '95% cotton / 5% metallic yarn' },
      { label: 'Weight', value: '450 – 560 GSM' },
      { label: 'Care', value: 'Gentle wash 30°C; no tumble' },
      { label: 'Colours', value: 'Champagne, silver, copper threads on 6 grounds' },
      { label: 'Packing', value: 'Gift-ready polybag; 25 pcs per carton' },
    ],
    industries: ['Gifting & E-commerce', 'Hospitality & Hotels'],
    certifications: ['OEKO-TEX', 'REACH'],
    tags: ['Festive', 'Shimmer'],
    minOrderQty: '200 pcs per colourway',
    featured: false,
    sortOrder: 43,
  },
];

const INDUSTRIES = [
  {
    name: 'Hospitality & Hotels',
    description: 'Bath, rug and cushion programmes for hotels, resorts, spas and serviced apartments — built for commercial laundering.',
    sortOrder: 1,
    subIndustries: [
      {
        name: 'Hotels & Resorts',
        applications: [
          { name: 'Guest-bathroom bath mats', note: '60°C wash-safe, reversible weaves' },
          { name: 'Lobby & lounge cushions', note: 'Hospitality-grade velvets, 25k Martindale' },
          { name: 'Suite rugs & runners', note: 'Custom sizes up to 400 cm' },
        ],
      },
      {
        name: 'Spas & Wellness',
        applications: [
          { name: 'Fast-dry waffle mats', note: 'Ready again within hours' },
          { name: 'Meditation floor cushions', note: 'Quilted, fill-stable' },
        ],
      },
      {
        name: 'Restaurants & Cafés',
        applications: [
          { name: 'Pouf seating for patios', note: '100 kg static-load tested' },
          { name: 'Washable flatweave runners', note: 'Domestic-size washable dhurries' },
        ],
      },
    ],
  },
  {
    name: 'Retail & Private Label',
    description: 'Own-brand ranges developed to your palette, labels and price tiers — from bath sets to bed-end throws.',
    sortOrder: 2,
    subIndustries: [
      {
        name: 'Retail Chains',
        applications: [
          { name: 'Bath mat programme', note: 'Pantone-matched, batch-consistent' },
          { name: 'Throw wall assortment', note: 'Three yarn tiers per shape' },
        ],
      },
      {
        name: 'Private Label Brands',
        applications: [
          { name: 'Woven-label & hem embroidery', note: 'Applied in-house' },
          { name: 'Seasonal colour drops', note: 'Labdips in 5 working days' },
        ],
      },
      {
        name: 'Department Stores',
        applications: [
          { name: 'Coordinate ranges', note: 'Mat + towel + cushion shade matching' },
          { name: 'Volume shaggy rugs', note: 'Consistent loom quality, volume pricing' },
        ],
      },
    ],
  },
  {
    name: 'Interior Studios & Designers',
    description: 'Specification-grade rugs, poufs and cushions for FF&E schedules, staging and model homes.',
    sortOrder: 3,
    subIndustries: [
      {
        name: 'Residential Projects',
        applications: [
          { name: 'Custom tufted rugs', note: 'Buyer artwork converted in 10 days' },
          { name: 'Texture-first cushions', note: 'Boucle, slub and jacquard palettes' },
        ],
      },
      {
        name: 'Commercial Interiors',
        applications: [
          { name: 'Contract poufs & seating', note: 'Load-tested, spot-cleanable' },
          { name: 'Light-fast velvets', note: 'Grade 4+ for sunlit lobbies' },
        ],
      },
      {
        name: 'Home Staging',
        applications: [
          { name: 'Neutral rug & throw kits', note: 'Fast-ship stock shades' },
        ],
      },
    ],
  },
  {
    name: 'Export & Distribution',
    description: 'Container-programme supply for importers and wholesalers — flat-packed dhurries, baled jute and roll-packed rugs.',
    sortOrder: 4,
    subIndustries: [
      {
        name: 'Importers & Wholesalers',
        applications: [
          { name: 'Mixed-container loading', note: 'Flatweaves fold to minimal volume' },
          { name: 'Catalogue exclusives', note: 'Designs locked to a single buyer' },
        ],
      },
      {
        name: 'Chain Retail Supply',
        applications: [
          { name: 'Replenishment programmes', note: 'Repeat-order shade matching' },
          { name: 'Compliance documentation', note: 'GRS / OEKO-TEX certificates per lot' },
        ],
      },
    ],
  },
  {
    name: 'Gifting & E-commerce',
    description: 'Parcel-friendly, gift-ready pieces with low MOQs and fast sampling for online-first brands.',
    sortOrder: 5,
    subIndustries: [
      {
        name: 'Online-First Brands',
        applications: [
          { name: 'Parcel-size rugs & throws', note: 'Fold-flat, lightweight shipping' },
          { name: 'New prints in 7 days', note: 'Rapid sampling for drops' },
        ],
      },
      {
        name: 'Curated Gifting',
        applications: [
          { name: 'Premium boxed throws', note: 'Tote or kraft-band presentation' },
          { name: 'One-of-a-kind patchwork', note: 'Unique pieces, GRS content' },
        ],
      },
    ],
  },
];

const STATS = [
  { key: 'export_markets', value: 18, suffix: '+', label: 'Export markets served', caption: 'Active buyers across 4 continents', order: 1 },
  { key: 'skus', value: 240, suffix: '+', label: 'Active SKUs', caption: 'Bath, cushion, pouf, rug and throw lines', order: 2 },
  { key: 'developments', value: 95, suffix: '+', label: 'Developments shipped last year', caption: 'New samples converted to orders', order: 3 },
  { key: 'looms', value: 120, suffix: '+', label: 'Artisans & loom stations', caption: 'Handloom, tufting and braiding capacity', order: 4 },
];

const TESTIMONIALS = [
  {
    quote:
      'Our housekeeping team was replacing bath mats every quarter. Shakti’s reversible cotton mats have held their pile through a full year of 60°C washes — and the shade still matches our towel programme.',
    name: 'Priya Nair',
    role: 'Director of Housekeeping Procurement',
    company: 'Meridian Hotels & Resorts',
    city: 'Dubai, UAE',
    featured: true,
  },
  {
    quote:
      'We needed a 160 × 230 tufted rug matched to our client’s artwork in three weeks for a model-home handover. Tufting maps came in ten days, labdips in five — the rugs landed a week early.',
    name: 'Jonas Feld',
    role: 'Principal Designer',
    company: 'Feld Interior Studio',
    city: 'Copenhagen, Denmark',
    featured: true,
  },
  {
    quote:
      'The flatweave dhurries fold down to almost nothing, so our container costs dropped noticeably. Repeat orders arrive with identical shades — that consistency is rare in handloom.',
    name: 'Sarah Whitfield',
    role: 'Head of Sourcing',
    company: 'Whitfield Home Distribution',
    city: 'Manchester, UK',
    featured: true,
  },
];

const CERTIFICATES = [
  {
    key: 'OEKO-TEX',
    name: 'OEKO-TEX Standard 100',
    description: 'Bath, rug, cushion and throw articles tested for harmful substances — skin-safe for every room.',
    fileUrl: '',
    fileName: '',
  },
  {
    key: 'GRS',
    name: 'GRS — Global Recycled Standard',
    description: 'Certified recycled content for our sherpa throws, patchwork poufs and recycled-fill cushions.',
    fileUrl: '',
    fileName: '',
  },
  {
    key: 'GOTS',
    name: 'GOTS — Organic Textile Standard',
    description: 'Organic cotton dhurries, throws and handloom pieces processed per GOTS chemical restrictions.',
    fileUrl: '',
    fileName: '',
  },
  {
    key: 'ISO 9001',
    name: 'ISO 9001:2015',
    description: 'Quality management across weaving, tufting, stitching and dispatch — audited annually.',
    fileUrl: '',
    fileName: '',
  },
  {
    key: 'SEDEX',
    name: 'SEDEX / SMETA 4-Pillar',
    description: 'Social-compliance audit covering our weaver clusters, stitching units and dispatch operations.',
    fileUrl: '',
    fileName: '',
  },
  {
    key: 'REACH',
    name: 'REACH Declaration',
    description: 'SVHC-free declarations available per shipment on request.',
    fileUrl: '',
    fileName: '',
  },
];

/*
 * Hero slider slides — exactly what the homepage hero renders.
 * Editable via Admin → Hero (including image upload).
 */
const HERO_SLIDES = [
  {
    img: '/hero/hero-1.jpg',
    alt: 'Artisan weaving a vibrant rug on a traditional handloom',
    eyebrow: 'Crafted by Hand',
    line1: 'Woven by Artisans.',
    line2: 'Made to Last.',
    desc: 'Rooted in traditional weaving techniques, every textile carries the skill, patience, and story of the hands that created it.',
    ctaLabel: 'Meet Our Artisans',
    ctaTo: '/about',
    secondaryLabel: 'Explore Collection',
    secondaryTo: '/products',
    sortOrder: 1,
    active: true,
  },
  {
    img: '/hero/hero-2.jpg',
    alt: 'Colourful handcrafted cushions arranged on a sofa',
    eyebrow: 'Texture • Colour • Comfort',
    line1: 'Add Character',
    line2: 'to Every Corner.',
    desc: 'Thoughtfully designed cushions and textiles that bring colour, texture, and personality into your everyday spaces.',
    ctaLabel: 'Shop Cushions',
    ctaTo: '/products',
    secondaryLabel: '',
    secondaryTo: '',
    sortOrder: 2,
    active: true,
  },
  {
    img: '/hero/hero-3.jpg',
    alt: 'Rolls of handcrafted rugs in rich traditional patterns',
    eyebrow: 'The Art of Textiles',
    line1: 'Timeless Patterns.',
    line2: 'Richer Spaces.',
    desc: 'Explore a curated collection of handcrafted rugs and textiles, where traditional artistry meets contemporary interiors.',
    ctaLabel: 'View Collection',
    ctaTo: '/products',
    secondaryLabel: 'Our Story',
    secondaryTo: '/about',
    sortOrder: 3,
    active: true,
  },
  {
    img: '/hero/hero-4.jpg',
    alt: 'Corner of a living space styled with handwoven cushions and rugs',
    eyebrow: 'Crafted with Character',
    line1: 'Every Thread',
    line2: 'Tells a Story.',
    desc: 'From intricate geometric patterns to rich earthy tones, our textiles are designed with a deep appreciation for traditional craftsmanship.',
    ctaLabel: 'Explore Textiles',
    ctaTo: '/products',
    secondaryLabel: '',
    secondaryTo: '',
    sortOrder: 4,
    active: true,
  },
  {
    img: '/hero/hero-5.jpg',
    alt: 'Close-up of a handwoven rug with tassels and geometric weave',
    eyebrow: 'Handcrafted for Your Space',
    line1: 'Bring Home the Beauty',
    line2: 'of Handmade Textiles.',
    desc: 'Discover richly woven rugs, cushions, and textiles crafted to bring warmth, character, and timeless style to every corner.',
    ctaLabel: 'Explore Collection',
    ctaTo: '/products',
    secondaryLabel: 'Discover Our Craft',
    secondaryTo: '/about',
    sortOrder: 5,
    active: true,
  },
];

/*
 * Site content blocks — homepage text sections, all editable via Admin → Content.
 */
const SITE_CONTENT = {
  welcome: {
    eyebrow: 'Welcome to Shakti Textile',
    title: 'We Weave What You Imagine',
    paragraphs: [
      'At Shakti Textile, we bring craftsmanship, creativity, and comfort together to create high-quality home furnishing products. As a trusted manufacturer of rugs, carpets, cushions, throws, and bathmats, we combine traditional techniques with modern designs to enhance every living space.',
      'With a strong focus on quality, sustainability, and innovation, our collections are designed to meet the diverse needs of global markets. Every product is crafted with care, using premium materials and attention to detail to ensure lasting beauty and durability.',
      'Whether you are looking to elevate a cozy corner or transform an entire room, Shakti Textile is your reliable partner for stylish and functional home decor solutions.',
    ],
    ctaLabel: 'More About Us',
    ctaTo: '/about',
    active: true,
  },
  process: {
    eyebrow: 'How we work',
    title: 'Find the fabric, enjoy the process and the results',
    description: 'A customer-centric approach to ensure the highest quality and satisfaction at every stage — from initial consultation to the final product.',
    steps: [
      { label: 'Consultation', desc: 'Get expert consultation to bring your ideas for rugs, carpets and throw pillows to life.', tag: 'Step 1' },
      { label: 'Choose Your Material', desc: 'Select from a wide range of high-quality materials to perfectly suit your product vision and comfort needs.', tag: 'Step 2' },
      { label: 'Production', desc: 'Experience precision manufacturing and expert craftsmanship for premium rugs, cushions and throws.', tag: 'Step 3' },
      { label: 'The Final Result', desc: 'Our final products reflect a perfect blend of durability, design, and innovation — crafted to elevate any space.', tag: 'Step 4' },
    ],
    active: true,
  },
  closingCta: {
    title: 'Send us your specification.',
    highlight: 'Hold a sample in 7 days.',
    description: 'Meter samples with lab data, or a full export quote — the export desk replies within 24 hours.',
    primaryLabel: 'Request a Sample',
    whatsappLabel: 'Get a Quote on WhatsApp',
    active: true,
  },
  trustedBy: {
    eyebrow: 'Trusted by',
    title: 'Buyers who audit before they order',
    partners: [
      'Aurelia Intimatewear',
      'Weber Outdoor GmbH',
      'Pacific Activewear',
      'Mumbai Bag Co.',
      'Helsa Medical',
      'TexStyle London',
      'Nova Luggage',
      'Kaya Babywear',
    ],
    active: true,
  },
  about: {
    eyebrow: 'Welcome to Shakti Textile',
    title: 'We Weave What You Imagine',
    intro: 'At Shakti Textile, we bring craftsmanship, creativity, and comfort together to create high-quality home furnishing products. As a trusted manufacturer of rugs, carpets, cushions, throws, and bathmats, we combine traditional techniques with modern designs to enhance every living space.',
    craftedTitle: 'Crafted with care',
    craftedText: 'With a strong focus on quality, sustainability, and innovation, our collections are designed to meet the diverse needs of global markets. Every product is crafted with care, using premium materials and attention to detail to ensure lasting beauty and durability. Whether you are looking to elevate a cozy corner or transform an entire room, Shakti Textile is your reliable partner for stylish and functional home decor solutions.',
    milestones: [
      { year: '1994', text: 'Founded as a family weaving workshop serving local traders in Panipat.' },
      { year: '2001', text: 'First export order — handloom dhurries to a UK home retailer.' },
      { year: '2009', text: 'In-house dyeing and finishing; ISO 9001 certification.' },
      { year: '2015', text: 'Hand-tufting and stitching units commissioned; OEKO-TEX Standard 100.' },
      { year: '2020', text: 'GRS-certified recycled cotton and polyester programmes; solar 40% of load.' },
      { year: '2024', text: '120+ artisan & loom stations, buyers in 18+ countries.' },
    ],
    values: [
      { title: 'Unmatched Quality', text: 'Every product is crafted with premium materials and attention to detail, ensuring durability and a refined finish.' },
      { title: 'Diverse Product Range', text: 'From rugs and carpets to cushions, throws and bathmats — a complete range of textile solutions to elevate any space.' },
      { title: 'Custom Designs', text: 'Every market is different. That is why we offer flexible, customizable designs to suit your unique needs and tastes.' },
      { title: 'Skilled Craftsmanship', text: 'Our experienced artisans bring traditional techniques and modern innovation together to create standout pieces.' },
      { title: 'Timely Delivery', text: 'We value your time. A streamlined production process and efficient logistics ensure timely delivery without compromising quality.' },
      { title: 'Sustainable Practices', text: 'We are committed to environmentally responsible manufacturing, using sustainable processes and ethical sourcing wherever possible.' },
    ],
    founders: [
      { name: 'Rameshbhai Patel', title: 'Founder & Chairman', philosophy: 'A loom never lies. If the weave coming off it is honest, the customer will feel it in the very first piece they unroll.', quote: 'We still weave every new design on our own floor for a week before we offer it to a buyer.' },
      { name: 'Nilesh Patel', title: 'Managing Director', philosophy: 'Export business is a promise business. The date we confirm is the date the container leaves.', quote: 'I personally review the dispatch board every morning — every season of on-time exports.' },
      { name: 'Priya Patel', title: 'Director — Exports & Compliance', philosophy: 'Certification is not paperwork; it is the buyer sleeping well in another timezone.', quote: 'Every certificate we hold is re-audited yearly, and buyers get the documents before they ask.' },
    ],
    active: true,
  },
  contactPage: {
    address: 'Panipat, Haryana, India',
    phone: '+91 70154 83332',
    phoneHref: '+917015483332',
    email: 'merchant@shaktitextile.com',
    hours: 'Monday–Saturday · 9:00–19:00 IST · replies within 24 h',
    active: true,
  },
  footer: {
    blurb: 'Manufacturer and exporter of handcrafted home textiles — rugs, carpets, cushions, poufs, bathmats and throws. Serving hospitality, retail and interior buyers across 18+ countries from India.',
    address: 'Panipat, Haryana, India',
    phone: '+91 70154 83332',
    phoneHref: '+917015483332',
    email: 'merchant@shaktitextile.com',
    tagline: 'We Weave What You Imagine — from the heart of Panipat',
    active: true,
  },
};

module.exports = { PRODUCTS, INDUSTRIES, STATS, TESTIMONIALS, CERTIFICATES, HERO_SLIDES, SITE_CONTENT };
